# PANDAS II

In [1]:
import pandas as pd

In [ ]:
#pd.series

data  = [1,2,3,4,5,6]

s1 = pd.Series(data)
print(s1)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [3]:
## creating custom index

s2= pd.Series(data, index=["a","b","c","d", "e", "f"], name="Numbers")
print(s2)

a    1
b    2
c    3
d    4
e    5
f    6
Name: Numbers, dtype: int64

In [4]:
data = {"a", 10, "b", 20, "c", 30}
s3= pd.Series(data)
print(s3)

TypeError: 'set' type is unordered

In [5]:
import numpy as np
arr= np.array([1,2,3,4,5,6])
s4=pd.Series(arr)
print(s4)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [6]:
s5=pd.Series([1,2,3,4,5,6], index = ["a","b","c","d", "e", "f"], name="scores")

In [7]:
print(s5.index)
print(s5.values)
print(s5.dtype)
print(s5.name)
print(s5.shape)
type(s5.shape)

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='str')
[1 2 3 4 5 6]
int64
scores
(6,)

tuple

## Series indexing and & accessing

In [8]:
## 1. Positional indexing

print(s5.values[0])
print(s5.values[3])

1
4

#### 1. iloc positional based indexing

In [9]:
## iloc gets rows (and / or columns ) at integer locations

print(s5.iloc[0])

1

In [10]:
## iloc gets rows (and / or columns ) at integer locations

print(s5.iloc[1:3])

b    2
c    3
Name: scores, dtype: int64

#### 2. label based indexing

#####  - loc gets rows (and/ or column) with particular labels

In [11]:
print(s5["c"])

3

In [12]:
print(s5["a"])

1

In [13]:
print(s5["e"])

5

In [16]:

print(s5[["b","d"]])

b    2
d    4
Name: scores, dtype: int64

In [17]:
## .loc[] uses the label/ index name not position
print(s5.loc[["b","e"]])

b    2
e    5
Name: scores, dtype: int64

In [18]:
s3=pd.Series([1,2,3,4,5,6]) ## index = ["a","b","c","d", "e", "f"], name="scores")

In [19]:
s3.iloc[[1,2]]

1    2
2    3
dtype: int64

In [21]:
s3.iloc[1:3]

1    2
2    3
dtype: int64

In [22]:
s3.loc[[1,3]]

1    2
3    4
dtype: int64

### DataFrames

In [23]:
data ={
    "Name" : ["Alfred", "Nii", "Ama"],
    "Age": [30,3,35],
    "City":["Osu", "Accra", "Anyako"]
}

df = pd.DataFrame(data)
print(df)

     Name  Age    City
0  Alfred   30     Osu
1     Nii    3   Accra
2     Ama   35  Anyako

In [24]:
df

     Name  Age    City
0  Alfred   30     Osu
1     Nii    3   Accra
2     Ama   35  Anyako

In [25]:
records =[

    {"Name": "Alfred", "Age":30, "City":"Osu"},
    {"Name": "Nii", "Age":3, "City":"Accra"},
    {"Name": "Ama", "Age":35, "City":"Anyako"},

]

df= pd.DataFrame(records)

df

     Name  Age    City
0  Alfred   30     Osu
1     Nii    3   Accra
2     Ama   35  Anyako

In [29]:
arr = np.array([[1,2], [4,5], [6,7]])
data = pd.DataFrame(arr, index=["a", "b", "c"])
data

   0  1
a  1  2
b  4  5
c  6  7

In [27]:
data ={
    "Name" : ["Alfred", "Nii", "Ama"],
    "Age": [30,3,35],
    "City":["Osu", "Accra", "Anyako"]
}

df = pd.DataFrame(data)
print(df)

     Name  Age    City
0  Alfred   30     Osu
1     Nii    3   Accra
2     Ama   35  Anyako

In [ ]:
print(df["Name"])  ## data frame with one column

0    Alfred
1       Nii
2       Ama
Name: Name, dtype: str

In [ ]:
print(df[["Name", "Age"]]) ## data frame with two columns

     Name  Age
0  Alfred   30
1     Nii    3
2     Ama   35

In [33]:
## accessing the first row
print(df.iloc[0]) ## row by integer index level
print("===============")
print(df.loc[0]) ## row by index label

Name    Alfred
Age         30
City       Osu
Name: 0, dtype: object
===============
Name    Alfred
Age         30
City       Osu
Name: 0, dtype: object

# Working with real data set

In [34]:

titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(titanic_dataset_github_url)

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [35]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [36]:
df[["Name", "Sex"]]

                                                  Name     Sex
0                              Braund, Mr. Owen Harris    male
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2                               Heikkinen, Miss. Laina  female
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4                             Allen, Mr. William Henry    male
..                                                 ...     ...
886                              Montvila, Rev. Juozas    male
887                       Graham, Miss. Margaret Edith  female
888           Johnston, Miss. Catherine Helen "Carrie"  female
889                              Behr, Mr. Karl Howell    male
890                                Dooley, Mr. Patrick    male

[891 rows x 2 columns]

In [37]:
df.loc[0]["Name"]

'Braund, Mr. Owen Harris'

In [38]:
df.iloc[:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [40]:
df.iloc[0,3] ### the index 0 column 3

'Braund, Mr. Owen Harris'

In [42]:
df["Age"]>70 ## only boolean index of passengers ages greater than 70

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [ ]:
## filtering the dataset
df[df["Age"]> 70] ### Gives us the actual values

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [44]:
older_passengers = df[df["Age"]> 70] 
older_passengers

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [45]:
older_passengers.shape

(5, 12)

In [47]:
older_passengers.info()

<class 'pandas.DataFrame'>
Index: 5 entries, 96 to 851
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  5 non-null      int64
 1   Survived     5 non-null      int64
 2   Pclass       5 non-null      int64
 3   Name         5 non-null      str
 4   Sex          5 non-null      str
 5   Age          5 non-null      float64
 6   SibSp        5 non-null      int64
 7   Parch        5 non-null      int64
 8   Ticket       5 non-null      str
 9   Fare         5 non-null      float64
 10  Cabin        2 non-null      str
 11  Embarked     5 non-null      str
dtypes: float64(2), int64(5), str(5)
memory usage: 520.0 bytes

In [48]:
older_passengers.describe()

       PassengerId  Survived    Pclass        Age  SibSp  Parch       Fare
count     5.000000  5.000000  5.000000   5.000000    5.0    5.0   5.000000
mean    438.200000  0.200000  1.800000  73.300000    0.0    0.0  25.936680
std     328.292096  0.447214  1.095445   3.993745    0.0    0.0  18.086844
min      97.000000  0.000000  1.000000  70.500000    0.0    0.0   7.750000
25%     117.000000  0.000000  1.000000  71.000000    0.0    0.0   7.775000
50%     494.000000  0.000000  1.000000  71.000000    0.0    0.0  30.000000
75%     631.000000  0.000000  3.000000  74.000000    0.0    0.0  34.654200
max     852.000000  1.000000  3.000000  80.000000    0.0    0.0  49.504200

In [49]:
older_passengers["Age"].describe()

count     5.000000
mean     73.300000
std       3.993745
min      70.500000
25%      71.000000
50%      71.000000
75%      74.000000
max      80.000000
Name: Age, dtype: float64

In [ ]:
## females who survived

## sex = female and survived = 1

(df["Sex"]== "female") & (df["Survived"] == 1 )  ### will just return either true or false

In [50]:
## females who survived

## sex = female and survived = 1

df[(df["Sex"]== "female") & (df["Survived"] == 1 )]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [52]:
### get name and age of females who survived
female_survivors_subset = df[(df["Sex"]== "female") & (df["Survived"] == 1 )][["Name", "Age"]]
female_survivors_subset

                                                  Name   Age
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                  Nasser, Mrs. Nicholas (Adele Achem)  14.0
..                                                 ...   ...
874              Abelson, Mrs. Samuel (Hannah Wizosky)  28.0
875                   Najib, Miss. Adele Kiamie "Jane"  15.0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0
880       Shelley, Mrs. William (Imanita Parrish Hall)  25.0
887                       Graham, Miss. Margaret Edith  19.0

[233 rows x 2 columns]

In [53]:
### get name and age of females who survived using loc
## loc requires the labels 
## df.loc[label, ["Name", "Age"]]
df.loc[(df["Sex"]== "female") & (df["Survived"] == 1 ), ["Name", "Age"]]

                                                  Name   Age
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                  Nasser, Mrs. Nicholas (Adele Achem)  14.0
..                                                 ...   ...
874              Abelson, Mrs. Samuel (Hannah Wizosky)  28.0
875                   Najib, Miss. Adele Kiamie "Jane"  15.0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0
880       Shelley, Mrs. William (Imanita Parrish Hall)  25.0
887                       Graham, Miss. Margaret Edith  19.0

[233 rows x 2 columns]

### Slicing rows and columns together

In [54]:
### Slicing rows and columns together

## row 0 to 4 only name and age

df.loc[:4, ["Name", "Age"]]

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0

In [55]:
### first 3 rows and first 2 columns

df.iloc[0:3, 0:2]

   PassengerId  Survived
0            1         0
1            2         1
2            3         1

In [56]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [58]:
## first 3 rows and columns survivied as  the first column and name column

df.iloc[0:3, [3,1]]

                                                Name  Survived
0                            Braund, Mr. Owen Harris         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...         1
2                             Heikkinen, Miss. Laina         1

In [59]:
df.loc[0:3, ["Name", "Survived"]]

                                                Name  Survived
0                            Braund, Mr. Owen Harris         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...         1
2                             Heikkinen, Miss. Laina         1
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)         1

In [60]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Create or set my own index (create custom index)

In [64]:
df_by_passenger_id = df.set_index("PassengerId",drop=False)
df_by_passenger_id.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,,
1,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [65]:
df_by_passenger_id = df.reset_index()
df_by_passenger_id.head()

,index,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S